### ISSUE TITLE
バックアップ

### ISSUE THREAD

**Issue by hata6502** [blue-hood/pencil#12]

**Comment by Hato6502** [comment]
Session Storage と サーバーバックアップ。

**Comment by Hato6502** [comment]
サーバー側へは手動で3スロット。

**Comment by hata6502** [comment]
960x720x4 = 2.64MB (Base64 の場合 3.52 MB)。

サーバーアップロード時は LocalStorage を消す。
サーバーダウンロード時、LocalStorage が残っている場合はどちらかを選ばせる必要がある。

**Comment by hata6502** [comment]
ページ移動前にbackupする。

**Comment by hata6502** [comment]
背景画像の保存は見送る。
